platform :osx, '10.9'
use_frameworks!

target 'ObjcSuperMessagingProxyTests' do
  pod 'SGVSuperMessagingProxy/Objective-C', :path => "../"
end

target 'SwiftSuperMessagingProxyTests' do
  pod 'SGVSuperMessagingProxy/Swift', :path => "../"
end

post_install do |installer|
  system("rm -rf Pods/SGVSuperMessagingProxy")
  system("mkdir -p Pods/SGVSuperMessagingProxy/")
  system("ln -s $(pwd -L)/../Pod/ Pods/SGVSuperMessagingProxy")
end
