platform :osx, '10.9'
use_frameworks!

target 'ObjcSuperMessagingProxyTests' do
  pod 'SGVSuperMessagingProxy/Objective-C', :path => "../"
end

target 'SwiftSuperMessagingProxyTests' do
  pod 'SGVSuperMessagingProxy/Swift', :path => "../"
end

post_install do |installer|
  podfile_dir = File.expand_path(File.dirname(__FILE__))
  system("rm -rf '#{podfile_dir}/Pods/SGVSuperMessagingProxy'")
  system("mkdir -p '#{podfile_dir}/Pods/SGVSuperMessagingProxy'")
  system("ln -s '#{podfile_dir}/../Pod/' '#{podfile_dir}/Pods/SGVSuperMessagingProxy'")
end
