platform :ios, '8.0'
use_frameworks!

target 'SGVSuperMessagingProxyExample' do
  pod 'SGVSuperMessagingProxy', :path => "../"

  target 'SGVSuperMessagingProxyTests' do
    inherit! :search_paths
  end
end
