language: objective-c
osx_image: xcode7.3
cache: cocoapods
notifications:
  email: false
rvm: 2.3
install:
- bundle install
podfile: Example/Podfile
script:
- set -o pipefail
- xcodebuild test -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme ObjcSuperMessagingProxyTests ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild test -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme SwiftSuperMessagingProxyTests ONLY_ACTIVE_ARCH=NO | xcpretty
