language: objective-c
osx_image: xcode9.3beta
notifications:
  email: false
script:
- set -o pipefail
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme OSXObjcTests -destination "platform=OS X,arch=x86_64" test | xcpretty
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme OSXSwiftTests -destination "platform=OS X,arch=x86_64" test | xcpretty
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme iOSObjcTests -destination "platform=iOS Simulator,name=iPhone 4s,OS=latest" test | xcpretty
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme iOSObjcTests -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" test | xcpretty
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme iOSSwiftTests -destination "platform=iOS Simulator,name=iPhone 4s,OS=latest" test | xcpretty
- xcodebuild -workspace Example/SuperMessagingProxyTests.xcworkspace -scheme iOSSwiftTests -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" test | xcpretty
