language: objective-c
osx_image: xcode7.3
cache: cocoapods
notifications:
  email: false
rvm: 2.3
install:
- bundle install
- pod install --project-directory=Example
script:
- set -o pipefail
- scan -w Example/SuperMessagingProxyTests.xcworkspace -s ObjcSuperMessagingProxyTests -r true --destination "platform=OS X,arch=x86_64"
- scan -w Example/SuperMessagingProxyTests.xcworkspace -s SwiftSuperMessagingProxyTests -r true --destination "platform=OS X,arch=x86_64"
