//
//  SwiftTrampolines.c
//  Pods
//
//  Created by Aleksandr Gusev on 29/05/16.
//
//

#include "TrampolineMacros.h"

SGVDefineTrampolineFuction(SGVObjcMsgSendSuperTrampolineSwift, _objc_msgSendSuper, SGVSelfLocation, SGVIvarOffsetSwift)
SGVDefineTrampolineFuction(SGVObjcMsgSendSuper2TrampolineSwift, _objc_msgSendSuper2, SGVSelfLocation, SGVIvarOffsetSwift)

#if defined(__arm64__)
void SGVObjcMsgSendSuperStretTrampolineSwift(void) {};
void SGVObjcMsgSendSuper2StretTrampolineSwift(void) {};
#else
SGVDefineTrampolineFuction(SGVObjcMsgSendSuperStretTrampolineSwift, _objc_msgSendSuper_stret, SGVSelfLocationStret, SGVIvarOffsetSwift)
SGVDefineTrampolineFuction(SGVObjcMsgSendSuper2StretTrampolineSwift, _objc_msgSendSuper2_stret, SGVSelfLocationStret, SGVIvarOffsetSwift)
#endif

SGVDefineAddressOfTrampolineFunctionFunction(SGVAddressOfObjcMsgSendSuperTrampolineSwift, SGVObjcMsgSendSuperTrampolineSwift)

SGVDefineAddressOfTrampolineFunctionFunction(SGVAddressOfObjcMsgSendSuper2TrampolineSwift, SGVObjcMsgSendSuper2TrampolineSwift)

SGVDefineAddressOfTrampolineFunctionFunction(SGVAddressOfObjcMsgSendSuperStretTrampolineSwift, SGVObjcMsgSendSuperStretTrampolineSwift)

SGVDefineAddressOfTrampolineFunctionFunction(SGVAddressOfObjcMsgSendSuper2StretTrampolineSwift, SGVObjcMsgSendSuper2StretTrampolineSwift)
